version: '2'

services:

  mysql:
    container_name: mysql-5.6        # 指定容器的名称
    image: mysql:5.6                   # 指定镜像和版本
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: 'root'
      MYSQL_PASS: 'root'
    volumes:
        - "./db:/var/lib/mysql"
        - "./conf/my.cnf:/etc/my.cnf"
        - "./init:/docker-entrypoint-initdb.d/"