version: '2'
services:
  redis:
    image: sameersbn/redis:4.0.9-1
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/var/lib/redis
  mq:
    image: vromero/activemq-artemis:2.6.2-alpine
    restart: always
    environment:
      - ARTEMIS_USERNAME=hybris 
      - ARTEMIS_PASSWORD=123456
    ports:
      - 61616:61616
      - 8161:8161
    volumes:
      - ./data/mq:/var/lib/artemis/data
